# Generated by Django 5.0.7 on 2024-07-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_product_category_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PO_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
