# Generated by Django 5.0.7 on 2024-07-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_product_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
