# Generated by Django 5.0.7 on 2024-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_order_staff_remove_order_status_order_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.CharField(editable=False, max_length=5, unique=True),
        ),
    ]
