# Generated by Django 5.0.7 on 2024-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_order_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
