# Generated by Django 5.0.7 on 2024-07-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_order_staff_remove_order_status_order_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
